theme: jekyll-theme-midnight
title: Kotatogram
description: an experimental Telegram Desktop fork
github:
  win_release: https://github.com/kotatogram/kotatogram-desktop/releases/download/k1.3.3/1.3.3.zip
  linux_release: https://github.com/kotatogram/kotatogram-desktop/releases/download/k1.3.3/1.3.3.tar.xz
show_downloads: true