name: Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'

jobs:
  build:
    name: Build site
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      BRANCH: "master"
    steps:
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          extended: true
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          submodules: true
          path: current
      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          path: target
      - name: Clean old files
        run: |
          cd target
          rm -rf *
      - name: Build Hugo site
        run: |
          cd current/hugo
          hugo --minify
      - name: Minify public JSON files
        run: |
          cd current
          ./minify.py
      - name: Copy public files
        run: |
          cp -r current/hugo/public/* target/
          cp -r current/public/* target/
      - name: Check for changes
        id: no_changes
        continue-on-error: true
        run: |
          cd target
          /usr/bin/git status | grep -q "nothing to commit, working tree clean"
      - name: Setting up credentials
        if: steps.no_changes.outcome == 'failure'
        run: |
          cd target
          /usr/bin/git config user.email ${{ secrets.COMMITER_EMAIL }}
          /usr/bin/git config user.name ${{ secrets.COMMITER_NAME }}
      - name: Commit changes
        if: steps.no_changes.outcome == 'failure'
        run: |
          cd target
          /usr/bin/git add -A
          /usr/bin/git commit -m "${{ github.event.head_commit.message }}"
      - name: Push changes to target
        if: steps.no_changes.outcome == 'failure'
        run: |
          cd target
          /usr/bin/git push "https://${{ secrets.KOTATO_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
