name: Build
on:
  push:
    branches:
      - dev
    paths-ignore:
      - 'README.md'

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-latest
    env:
      BRANCH: "master"
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
        with:
          path: current
      - name: Checkout target branch
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH }}
          path: target
      - name: Clean old files
        run: |
          cd target
          rm -rf *
      - name: Copy public files
        run: cp -r current/public/* target/
      - name: Check for changes
        run: |
          cd target
          git status | grep -q "nothing to commit, working tree clean" \
          || echo "::set-env name=HAS_CHANGES::1"
      - name: Setting up credentials
        if: ${{ env.HAS_CHANGES }}
        run: |
          cd target
          git config user.email ${{ secrets.COMMITER_EMAIL }}
          git config user.name ${{ secrets.COMMITER_NAME }}
      - name: Commit changes
        if: ${{ env.HAS_CHANGES }}
        run: |
          cd target
          git add -A
          git commit -m "${{ github.event.head_commit.message }}"
      - name: Push changes to target
        if: ${{ env.HAS_CHANGES }}
        run: |
          cd target
          git push "https://${{ secrets.KOTATO_TOKEN }}@github.com/${GITHUB_REPOSITORY}.git"
