name: Build
on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current branch
        uses: actions/checkout@v2
      - name: Checkout test
        uses: actions/checkout@v2
        with:
          ref: test
          path: gh-pages
      - name: Clean old files
        run: |
          cd gh-pages
          rm -rf *
      - name: Copy public files
        run: cp -r public/* gh-pages/
      - name: Get commit message
        run: |
          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
          echo "::set-env name=MESSAGE::$COMMIT_MESSAGE"
      - name: Commit changes
        run: |
          git config user.email ${{ secrets.COMMITER_EMAIL }}
          git config user.name ${{ secrets.COMMITER_NAME }}
          git add *
          git commit -m "$MESSAGE"
      - name: Push
        uses: ad-m/github-push-action@v0.5.0
        with:
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
